FROM node:latest
ENV NODE_ENV prod
ENV NODE_OPTIONS --openssl-legacy-provider
WORKDIR /app
COPY ./server/dist/ /app/
COPY ./server/configs/ /app/configs/
COPY ./server/resources/ /app/resources/
RUN npm config set registry https://registry.npm.aliyun.com/ \
  && npm install --unsafe-perm=true --allow-root
EXPOSE 4000
CMD [ "node", "./app.js" ]
