##return `[${database.name}]`*/
database="/*return project.database[1]*/"
username="/*return database.username*/"
password="/*return database.password*/"
host="/*return database.host*/"
port=0##return database.port*/
