##return `[${database.dbtype}]`*/
database="/*return database.db*/"
username="/*return database.username*/"
password="/*return database.password*/"
host="/*return database.host*/"
port=0##return database.port*/
