version = 1
prefix = "server-package"
type = "mongo"
sync=false
# sync = ['admin', 'database', 'dependency', 'component']
# inits = { admin = "./resources/database/admin.json", database = "./resources/database/database.json", dependency = "./resources/database/dependency.json", component = "./resources/database/component.json" }
