version=1
prefix="server-package"
type="mongo"
sync=false
# sync=['database', 'dependency']
# inits={ database = "./resources/database/database.json", dependency = "./resources/database/dependency.json" }
